//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class MainResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MainResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.MainResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إضافة رقم الهاتف.
        /// </summary>
        internal static string AddPhoneSuccess {
            get {
                return ResourceManager.GetString("AddPhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال رقم يسمح بالقسمة علي عدد الكتب في في نوع التحزيم.
        /// </summary>
        internal static string AllowDivisionForPackageValue {
            get {
                return ResourceManager.GetString("AllowDivisionForPackageValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة / تعديل طلب تحزيم.
        /// </summary>
        internal static string BookPackingTitle {
            get {
                return ResourceManager.GetString("BookPackingTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ عملية طباعة كتب.
        /// </summary>
        internal static string BookPrintingOperationEditFormTitle {
            get {
                return ResourceManager.GetString("BookPrintingOperationEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة عمليات طباعة الكتب.
        /// </summary>
        internal static string BookPrintingOperationTitle {
            get {
                return ResourceManager.GetString("BookPrintingOperationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تحزيم الكتب.
        /// </summary>
        internal static string BookRepack {
            get {
                return ResourceManager.GetString("BookRepack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعراض.
        /// </summary>
        internal static string btnBrowse {
            get {
                return ResourceManager.GetString("btnBrowse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجهيز حاوية مركز.
        /// </summary>
        internal static string btnContainerPreparation {
            get {
                return ResourceManager.GetString("btnContainerPreparation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة طلب تجهيز.
        /// </summary>
        internal static string btnPrepareForWithdraw {
            get {
                return ResourceManager.GetString("btnPrepareForWithdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة.
        /// </summary>
        internal static string btnPrint {
            get {
                return ResourceManager.GetString("btnPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تغيير كلمة المرور.
        /// </summary>
        internal static string ChangePasswordSuccess {
            get {
                return ResourceManager.GetString("ChangePasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد مدن مرتبطه بهذه المنطقة الإدارية يرجي حذفها أولا.
        /// </summary>
        internal static string CitiesAssociatedToState {
            get {
                return ResourceManager.GetString("CitiesAssociatedToState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المدينة توجد بالنظام.
        /// </summary>
        internal static string CityExistsCheck {
            get {
                return ResourceManager.GetString("CityExistsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات مرتبطه بهذه المدينة يرجى حذفها اولا.
        /// </summary>
        internal static string CityHasAssociatedData {
            get {
                return ResourceManager.GetString("CityHasAssociatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المدن.
        /// </summary>
        internal static string CityTitle {
            get {
                return ResourceManager.GetString("CityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الغاء البحث.
        /// </summary>
        internal static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طلب حاوية مركز.
        /// </summary>
        internal static string ContainerRequestEditFormTitle {
            get {
                return ResourceManager.GetString("ContainerRequestEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تجهيز حاويات المركز.
        /// </summary>
        internal static string ContainerRequestTitle {
            get {
                return ResourceManager.GetString("ContainerRequestTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حذف.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هل تريد حذف هذا البيان؟.
        /// </summary>
        internal static string DeleteMessage {
            get {
                return ResourceManager.GetString("DeleteMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تعديل.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ نوع الإختبار.
        /// </summary>
        internal static string EditFormExamTypeTitle {
            get {
                return ResourceManager.GetString("EditFormExamTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا البريد الإلكتروني موجود بالنظام.
        /// </summary>
        internal static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to   لا يمكن فتح الملف ({0}) يرجي التأكد من وجود الملف .
        /// </summary>
        internal static string EmailTemplateError {
            get {
                return ResourceManager.GetString("EmailTemplateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أدخل بريدك الألكتروني.
        /// </summary>
        internal static string EnterEmail {
            get {
                return ResourceManager.GetString("EnterEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال قيمة اقل من او تساوي كمية الطباعة للنموذج الواحد.
        /// </summary>
        internal static string EnterNumberLessThanBooksCount {
            get {
                return ResourceManager.GetString("EnterNumberLessThanBooksCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال قيمة اقل من او تساوي كمية الطباعة لنموذج A3.
        /// </summary>
        internal static string EnterNumberLessThanBooksCountA3 {
            get {
                return ResourceManager.GetString("EnterNumberLessThanBooksCountA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب إدخال النوع المخصص منه.
        /// </summary>
        internal static string EnterPackingParentID {
            get {
                return ResourceManager.GetString("EnterPackingParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حدث خطأ بالنظام.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن حذف هذا التحزيم يوجد بيانات مرتبطة به.
        /// </summary>
        internal static string ErrorDeletingPack {
            get {
                return ResourceManager.GetString("ErrorDeletingPack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ مركز إختبار.
        /// </summary>
        internal static string ExamCenterEditTitle {
            get {
                return ResourceManager.GetString("ExamCenterEditTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المركز يوجد بالنظام.
        /// </summary>
        internal static string ExamCenterExistsCheck {
            get {
                return ResourceManager.GetString("ExamCenterExistsCheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات مرتبطة بهذا المركز.
        /// </summary>
        internal static string ExamCenterHasAssociatedData {
            get {
                return ResourceManager.GetString("ExamCenterHasAssociatedData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ احتياجات مركز.
        /// </summary>
        internal static string ExamCenterItemNeedsEditFormTitle {
            get {
                return ResourceManager.GetString("ExamCenterItemNeedsEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضافة تعديل احتياجات لمركز اختبار.
        /// </summary>
        internal static string ExamCenterItemNeedsTitle {
            get {
                return ResourceManager.GetString("ExamCenterItemNeedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ احتياج لمركز اختبار.
        /// </summary>
        internal static string ExamCenterNeedsDetailEditFormTitle {
            get {
                return ResourceManager.GetString("ExamCenterNeedsDetailEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اضافة / تعديل احتياجات لمركز اختبار.
        /// </summary>
        internal static string ExamCenterNeedsDetailTitle {
            get {
                return ResourceManager.GetString("ExamCenterNeedsDetailTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ احتياجات مركز.
        /// </summary>
        internal static string ExamCenterNeedsEditFormTitle {
            get {
                return ResourceManager.GetString("ExamCenterNeedsEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادارة احتياجات المراكز.
        /// </summary>
        internal static string ExamCenterNeedsTitle {
            get {
                return ResourceManager.GetString("ExamCenterNeedsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة مراكز الإختبارات.
        /// </summary>
        internal static string ExamCenterTitle {
            get {
                return ResourceManager.GetString("ExamCenterTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يمكن تعديل رمز المركز.
        /// </summary>
        internal static string ExamCodeCantBeModified {
            get {
                return ResourceManager.GetString("ExamCodeCantBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ إختبار.
        /// </summary>
        internal static string ExamEditFormTitle {
            get {
                return ResourceManager.GetString("ExamEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الإختبار يوجد بالنظام.
        /// </summary>
        internal static string ExamExists {
            get {
                return ResourceManager.GetString("ExamExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ نموذج إختبار.
        /// </summary>
        internal static string ExamModelEditFormTitle {
            get {
                return ResourceManager.GetString("ExamModelEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا النموذج موجود بالنظام.
        /// </summary>
        internal static string ExamModelExists {
            get {
                return ResourceManager.GetString("ExamModelExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج الإختبار.
        /// </summary>
        internal static string ExamModels {
            get {
                return ResourceManager.GetString("ExamModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة نماذج الإختبارات.
        /// </summary>
        internal static string ExamModelTitle {
            get {
                return ResourceManager.GetString("ExamModelTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ فترة إختبار.
        /// </summary>
        internal static string ExamPeriodEditFormTitle {
            get {
                return ResourceManager.GetString("ExamPeriodEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة فترات اللإختبارات.
        /// </summary>
        internal static string ExamPeriodTitle {
            get {
                return ResourceManager.GetString("ExamPeriodTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ تخصص إختبار.
        /// </summary>
        internal static string ExamSpecialityEditFormTitle {
            get {
                return ResourceManager.GetString("ExamSpecialityEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة تخصصات الإختبارات.
        /// </summary>
        internal static string ExamSpecialityTitle {
            get {
                return ResourceManager.GetString("ExamSpecialityTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة الإختبارات.
        /// </summary>
        internal static string ExamTitle {
            get {
                return ResourceManager.GetString("ExamTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد نوع الاختبار هذا بالنظام.
        /// </summary>
        internal static string ExamTypeExists {
            get {
                return ResourceManager.GetString("ExamTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة أنواع الأختبارات.
        /// </summary>
        internal static string ExamTypeTitle {
            get {
                return ResourceManager.GetString("ExamTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف الدخول الخارجي.
        /// </summary>
        internal static string ExternalLoginRemoved {
            get {
                return ResourceManager.GetString("ExternalLoginRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد الهاتف لم يتم بنجاح.
        /// </summary>
        internal static string FailedToVerifyPhone {
            get {
                return ResourceManager.GetString("FailedToVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  راجع بريدك الإلكتروني لتعيين كلمة المرور الجديدة.
        /// </summary>
        internal static string ForgotPasswordConfirmationLabel {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد نسيان كلمة المرور.
        /// </summary>
        internal static string ForgotPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا تتذكر كلمة المرور؟ .
        /// </summary>
        internal static string ForgotPasswordPageTitle {
            get {
                return ResourceManager.GetString("ForgotPasswordPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود غير صحيح.
        /// </summary>
        internal static string InvalidCodeValidation {
            get {
                return ResourceManager.GetString("InvalidCodeValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد خطأ في البريد الاكتروني او كلمة المرور.
        /// </summary>
        internal static string InvalidLoginAttempt {
            get {
                return ResourceManager.GetString("InvalidLoginAttempt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to غير فعال.
        /// </summary>
        internal static string IsActiveFalse {
            get {
                return ResourceManager.GetString("IsActiveFalse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        internal static string IsActiveTrue {
            get {
                return ResourceManager.GetString("IsActiveTrue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا الحساب تم حجبه يرجى المحاولة لاحقا او الرجوع لإدارة الخدمات الالكترونية.
        /// </summary>
        internal static string LockoutMessage {
            get {
                return ResourceManager.GetString("LockoutMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حساب محجوب.
        /// </summary>
        internal static string LockoutTitle {
            get {
                return ResourceManager.GetString("LockoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نسيت كلمة المرور؟.
        /// </summary>
        internal static string LoginPageForgotPassword {
            get {
                return ResourceManager.GetString("LoginPageForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string LoginPagePassword {
            get {
                return ResourceManager.GetString("LoginPagePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        internal static string LoginPageRememberMe {
            get {
                return ResourceManager.GetString("LoginPageRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة الدخول.
        /// </summary>
        internal static string LoginPageTitle {
            get {
                return ResourceManager.GetString("LoginPageTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم او البريد الالكتروني.
        /// </summary>
        internal static string LoginPageUserName {
            get {
                return ResourceManager.GetString("LoginPageUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to خروج.
        /// </summary>
        internal static string Logoff {
            get {
                return ResourceManager.GetString("Logoff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المستخدمين.
        /// </summary>
        internal static string ManageUserTitle {
            get {
                return ResourceManager.GetString("ManageUserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to جديد.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد بيانات.
        /// </summary>
        internal static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to لا يوجد حزمه مختارة للاضافة.
        /// </summary>
        internal static string NoRepackItemsSelected {
            get {
                return ResourceManager.GetString("NoRepackItemsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم ليس موجود بالنظام.
        /// </summary>
        internal static string NoUserError {
            get {
                return ResourceManager.GetString("NoUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الترقيم بنجاح.
        /// </summary>
        internal static string NumberingPackSuccess {
            get {
                return ResourceManager.GetString("NumberingPackSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات نوع التحزيم هذا بالنظام.
        /// </summary>
        internal static string PackageTypeExists {
            get {
                return ResourceManager.GetString("PackageTypeExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة أنواع التحزيم.
        /// </summary>
        internal static string PackageTypeTitle {
            get {
                return ResourceManager.GetString("PackageTypeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ وزن الحزمة.
        /// </summary>
        internal static string PackageWeightEditFormTitle {
            get {
                return ResourceManager.GetString("PackageWeightEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة وزن الحزم.
        /// </summary>
        internal static string PackageWeightTitle {
            get {
                return ResourceManager.GetString("PackageWeightTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحزيم.
        /// </summary>
        internal static string PackCustomButton {
            get {
                return ResourceManager.GetString("PackCustomButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to صفحة {0} من {1} عدد السجلات {2}.
        /// </summary>
        internal static string PageSummaryText {
            get {
                return ResourceManager.GetString("PageSummaryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تحتوي علي الاقل على رقم واحد و علي حرف صغير من (a-z) و علي حرف كبير من (A-Z).
        /// </summary>
        internal static string PasswordCheckError {
            get {
                return ResourceManager.GetString("PasswordCheckError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك صحح الأخطاء.
        /// </summary>
        internal static string PleaseCorrectErrors {
            get {
                return ResourceManager.GetString("PleaseCorrectErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طباعة الباركود.
        /// </summary>
        internal static string PrintPacksTitle {
            get {
                return ResourceManager.GetString("PrintPacksTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to قياس.
        /// </summary>
        internal static string QiyasTitle {
            get {
                return ResourceManager.GetString("QiyasTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الاستلام بنجاح.
        /// </summary>
        internal static string ReceivedSuccessfully {
            get {
                return ResourceManager.GetString("ReceivedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام الحزم بمستودع التخزين.
        /// </summary>
        internal static string ReceiveExamPackTitle {
            get {
                return ResourceManager.GetString("ReceiveExamPackTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استلام طلبات الطباعة.
        /// </summary>
        internal static string ReceivePrinterOrderTitle {
            get {
                return ResourceManager.GetString("ReceivePrinterOrderTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم حذف رقم الهاتف.
        /// </summary>
        internal static string RemovePhoneSuccess {
            get {
                return ResourceManager.GetString("RemovePhoneSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يجب ادخال كلمة المرور.
        /// </summary>
        internal static string RequiredPassword {
            get {
                return ResourceManager.GetString("RequiredPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        internal static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إضغط هنا للدخول.
        /// </summary>
        internal static string ResetPasswordConfirmationMainClickHereLinkLabel {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationMainClickHereLinkLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم إعادة تعيين كلمة المرور بنجاح..
        /// </summary>
        internal static string ResetPasswordConfirmationMainLabel {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to من فضلك .
        /// </summary>
        internal static string ResetPasswordConfirmationMainPleaseLabel {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationMainPleaseLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد تغيير كلمة المرور.
        /// </summary>
        internal static string ResetPasswordConfirmationTitle {
            get {
                return ResourceManager.GetString("ResetPasswordConfirmationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string ResetPasswordInvalidCode {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود المستخدم غير صالح.
        /// </summary>
        internal static string ResetPasswordInvalidToken {
            get {
                return ResourceManager.GetString("ResetPasswordInvalidToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إعادة تعيين كلمة المرور.
        /// </summary>
        internal static string ResetPasswordTitle {
            get {
                return ResourceManager.GetString("ResetPasswordTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم الحفظ بنجاح.
        /// </summary>
        internal static string SaveSuccess {
            get {
                return ResourceManager.GetString("SaveSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ادخل بيانات البحث.
        /// </summary>
        internal static string SearchNullText {
            get {
                return ResourceManager.GetString("SearchNullText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقمك التأكيدي هو: .
        /// </summary>
        internal static string SecurityCodeMessage {
            get {
                return ResourceManager.GetString("SecurityCodeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال عن طريق.
        /// </summary>
        internal static string SendCodeSelectProviderLabel {
            get {
                return ResourceManager.GetString("SendCodeSelectProviderLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إرسال.
        /// </summary>
        internal static string SendCodeSubmit {
            get {
                return ResourceManager.GetString("SendCodeSubmit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ارسال الكود.
        /// </summary>
        internal static string SendCodeTitle {
            get {
                return ResourceManager.GetString("SendCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم وضع كلمة المرور.
        /// </summary>
        internal static string SetPasswordSuccess {
            get {
                return ResourceManager.GetString("SetPasswordSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تم تفعيل نظام الحماية الثنائي.
        /// </summary>
        internal static string SetTwoFactorSuccess {
            get {
                return ResourceManager.GetString("SetTwoFactorSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ منطقة إدارية.
        /// </summary>
        internal static string StateProvinceEditFormTitle {
            get {
                return ResourceManager.GetString("StateProvinceEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذه المنطقة الإدارية توجد بالنظام.
        /// </summary>
        internal static string StateProvinceExists {
            get {
                return ResourceManager.GetString("StateProvinceExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدارة المناطق الإدارية.
        /// </summary>
        internal static string StateProvinceTitle {
            get {
                return ResourceManager.GetString("StateProvinceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع الحزم لجميع أنواع التحزيم يجب ان يتساوى مع كمية الطباعة المحددة بطلب الطباعة .
        /// </summary>
        internal static string TotalPackGreaterThanOverallTotal {
            get {
                return ResourceManager.GetString("TotalPackGreaterThanOverallTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز تأكيد الحساب.
        /// </summary>
        internal static string TwoWayAuthTitle {
            get {
                return ResourceManager.GetString("TwoWayAuthTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حفظ مستخدم.
        /// </summary>
        internal static string UserEditFormTitle {
            get {
                return ResourceManager.GetString("UserEditFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يوجد بيانات مرتبطه بهذا المستخدم يرجى حذفها اولا.
        /// </summary>
        internal static string UserHasDependentData {
            get {
                return ResourceManager.GetString("UserHasDependentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to هذا المستخدم موجود بالنظام.
        /// </summary>
        internal static string UserNameExists {
            get {
                return ResourceManager.GetString("UserNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي ادخال سنة بين 1300 و 1500 .
        /// </summary>
        internal static string ValidYear {
            get {
                return ResourceManager.GetString("ValidYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to إدخل الكود التأكيدي.
        /// </summary>
        internal static string VerifyMainLabel {
            get {
                return ResourceManager.GetString("VerifyMainLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تحقق من المستخدم.
        /// </summary>
        internal static string VerifyTitle {
            get {
                return ResourceManager.GetString("VerifyTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to استعراض.
        /// </summary>
        internal static string View {
            get {
                return ResourceManager.GetString("View", resourceCulture);
            }
        }
    }
}
