//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "12.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ModelResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ModelResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ModelResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصص من.
        /// </summary>
        internal static string AllocatedFrom {
            get {
                return ResourceManager.GetString("AllocatedFrom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الكتب.
        /// </summary>
        internal static string BookCount {
            get {
                return ResourceManager.GetString("BookCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل عمليات تحزيم الكتب.
        /// </summary>
        internal static string BookPackingOperationID {
            get {
                return ResourceManager.GetString("BookPackingOperationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BookPackingOperationName {
            get {
                return ResourceManager.GetString("BookPackingOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookPackItemID.
        /// </summary>
        internal static string BookPackItemID {
            get {
                return ResourceManager.GetString("BookPackItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookPackItemModelID.
        /// </summary>
        internal static string BookPackItemModelID {
            get {
                return ResourceManager.GetString("BookPackItemModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookPackItemOperationID.
        /// </summary>
        internal static string BookPackItemOperationID {
            get {
                return ResourceManager.GetString("BookPackItemOperationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BookPackItemOperationName {
            get {
                return ResourceManager.GetString("BookPackItemOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل عمليات طباعة الكتب.
        /// </summary>
        internal static string BookPrintingOperationID {
            get {
                return ResourceManager.GetString("BookPrintingOperationID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string BookPrintingOperationName {
            get {
                return ResourceManager.GetString("BookPrintingOperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookRepackPackageID.
        /// </summary>
        internal static string BookRepackPackageID {
            get {
                return ResourceManager.GetString("BookRepackPackageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BookRepackPackageItemID.
        /// </summary>
        internal static string BookRepackPackageItemID {
            get {
                return ResourceManager.GetString("BookRepackPackageItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الكتب للنموذج الواحد.
        /// </summary>
        internal static string BooksPerPackage {
            get {
                return ResourceManager.GetString("BooksPerPackage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الكتب.
        /// </summary>
        internal static string BooksTotal {
            get {
                return ResourceManager.GetString("BooksTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رمز المركز.
        /// </summary>
        internal static string CenterCode {
            get {
                return ResourceManager.GetString("CenterCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل المدينة.
        /// </summary>
        internal static string CityID {
            get {
                return ResourceManager.GetString("CityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المدينة.
        /// </summary>
        internal static string CityName {
            get {
                return ResourceManager.GetString("CityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الكود.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تأكيد كلمة المرور.
        /// </summary>
        internal static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور يجب ان تكون متطابقة.
        /// </summary>
        internal static string ConfirmPasswordValidtion {
            get {
                return ResourceManager.GetString("ConfirmPasswordValidtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainerRequestID.
        /// </summary>
        internal static string ContainerRequestID {
            get {
                return ResourceManager.GetString("ContainerRequestID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ContainerRequestPackID.
        /// </summary>
        internal static string ContainerRequestPackID {
            get {
                return ResourceManager.GetString("ContainerRequestPackID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الدولة.
        /// </summary>
        internal static string CountryRegionCode {
            get {
                return ResourceManager.GetString("CountryRegionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الدولة.
        /// </summary>
        internal static string CountryRegionName {
            get {
                return ResourceManager.GetString("CountryRegionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنشئت بواسطة.
        /// </summary>
        internal static string CreatedBy {
            get {
                return ResourceManager.GetString("CreatedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ الإنشاء.
        /// </summary>
        internal static string CreatedDate {
            get {
                return ResourceManager.GetString("CreatedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to أنشئت بواسطة.
        /// </summary>
        internal static string CreatorID {
            get {
                return ResourceManager.GetString("CreatorID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الموظف.
        /// </summary>
        internal static string DisplayName {
            get {
                return ResourceManager.GetString("DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to البريد الإلكتروني.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي ادخال بريد إلكتروني صحيح.
        /// </summary>
        internal static string EmailValidation {
            get {
                return ResourceManager.GetString("EmailValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ النهاية.
        /// </summary>
        internal static string EndDate {
            get {
                return ResourceManager.GetString("EndDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamCenterID.
        /// </summary>
        internal static string ExamCenterID {
            get {
                return ResourceManager.GetString("ExamCenterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المركز.
        /// </summary>
        internal static string ExamCenterName {
            get {
                return ResourceManager.GetString("ExamCenterName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamCenterRequiredExamsID.
        /// </summary>
        internal static string ExamCenterRequiredExamsID {
            get {
                return ResourceManager.GetString("ExamCenterRequiredExamsID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الإختبار.
        /// </summary>
        internal static string ExamCode {
            get {
                return ResourceManager.GetString("ExamCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل الإختبارات.
        /// </summary>
        internal static string ExamID {
            get {
                return ResourceManager.GetString("ExamID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل مراكز الإختبارات.
        /// </summary>
        internal static string ExaminationCenterID {
            get {
                return ResourceManager.GetString("ExaminationCenterID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل نوع الإختبار.
        /// </summary>
        internal static string ExaminationTypeID {
            get {
                return ResourceManager.GetString("ExaminationTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد النماذج.
        /// </summary>
        internal static string ExamModelCount {
            get {
                return ResourceManager.GetString("ExamModelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل نماذج الإختبارات.
        /// </summary>
        internal static string ExamModelID {
            get {
                return ResourceManager.GetString("ExamModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نموذج الإختبار.
        /// </summary>
        internal static string ExamModelName {
            get {
                return ResourceManager.GetString("ExamModelName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج الاختبار.
        /// </summary>
        internal static string ExamModelNames {
            get {
                return ResourceManager.GetString("ExamModelNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نماذج الإختبار.
        /// </summary>
        internal static string ExamModels {
            get {
                return ResourceManager.GetString("ExamModels", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وصف الإختبار.
        /// </summary>
        internal static string ExamName {
            get {
                return ResourceManager.GetString("ExamName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل فترات الإختبارات.
        /// </summary>
        internal static string ExamPeriodID {
            get {
                return ResourceManager.GetString("ExamPeriodID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم الفترة.
        /// </summary>
        internal static string ExamPeriodName {
            get {
                return ResourceManager.GetString("ExamPeriodName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExamRequirementItemID.
        /// </summary>
        internal static string ExamRequirementItemID {
            get {
                return ResourceManager.GetString("ExamRequirementItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الطباعة لنموذج A3.
        /// </summary>
        internal static string ExamsNeededForA3 {
            get {
                return ResourceManager.GetString("ExamsNeededForA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الطباعة لنموذج A4.
        /// </summary>
        internal static string ExamsNeededForA4 {
            get {
                return ResourceManager.GetString("ExamsNeededForA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية المواد السمعية CD.
        /// </summary>
        internal static string ExamsNeededForCD {
            get {
                return ResourceManager.GetString("ExamsNeededForCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل تخصص الإختبار.
        /// </summary>
        internal static string ExamSpecialityID {
            get {
                return ResourceManager.GetString("ExamSpecialityID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تخصص الإختبار.
        /// </summary>
        internal static string ExamSpecialityName {
            get {
                return ResourceManager.GetString("ExamSpecialityName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل نوع الإختبار.
        /// </summary>
        internal static string ExamTypeID {
            get {
                return ResourceManager.GetString("ExamTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع الإختبار.
        /// </summary>
        internal static string ExamTypeName {
            get {
                return ResourceManager.GetString("ExamTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to السنة.
        /// </summary>
        internal static string ExamYear {
            get {
                return ResourceManager.GetString("ExamYear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الملف.
        /// </summary>
        internal static string FileNeedsPath {
            get {
                return ResourceManager.GetString("FileNeedsPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to فعال.
        /// </summary>
        internal static string IsActive {
            get {
                return ResourceManager.GetString("IsActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to منطقة إدارية فقط.
        /// </summary>
        internal static string IsOnlyStateProvince {
            get {
                return ResourceManager.GetString("IsOnlyStateProvince", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to التسلسل الأخير.
        /// </summary>
        internal static string LastBookSerial {
            get {
                return ResourceManager.GetString("LastBookSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد النماذج.
        /// </summary>
        internal static string ModelCount {
            get {
                return ResourceManager.GetString("ModelCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدلت بواسطة.
        /// </summary>
        internal static string ModifiedBy {
            get {
                return ResourceManager.GetString("ModifiedBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدلت بواسطة.
        /// </summary>
        internal static string ModifiedByID {
            get {
                return ResourceManager.GetString("ModifiedByID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ التعديل.
        /// </summary>
        internal static string ModifiedDate {
            get {
                return ResourceManager.GetString("ModifiedDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الاسم.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ملاحظات.
        /// </summary>
        internal static string Notes {
            get {
                return ResourceManager.GetString("Notes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الكتب للنموذج.
        /// </summary>
        internal static string NumberofBooksPerModel {
            get {
                return ResourceManager.GetString("NumberofBooksPerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الصفحات.
        /// </summary>
        internal static string NumberofPages {
            get {
                return ResourceManager.GetString("NumberofPages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الأقسام.
        /// </summary>
        internal static string NumberofSections {
            get {
                return ResourceManager.GetString("NumberofSections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل حالة الطلب.
        /// </summary>
        internal static string OperationStatusID {
            get {
                return ResourceManager.GetString("OperationStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        internal static string OperationStatusName {
            get {
                return ResourceManager.GetString("OperationStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحزمة.
        /// </summary>
        internal static string PackageCode {
            get {
                return ResourceManager.GetString("PackageCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحزم.
        /// </summary>
        internal static string PackageTotal {
            get {
                return ResourceManager.GetString("PackageTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحزم للنموذج.
        /// </summary>
        internal static string PackageTotalPerModel {
            get {
                return ResourceManager.GetString("PackageTotalPerModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل وزن التحزيم.
        /// </summary>
        internal static string PackageWeightID {
            get {
                return ResourceManager.GetString("PackageWeightID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن الحزمة.
        /// </summary>
        internal static string PackageWeightName {
            get {
                return ResourceManager.GetString("PackageWeightName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل التحزيم.
        /// </summary>
        internal static string PackagingTypeID {
            get {
                return ResourceManager.GetString("PackagingTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to نوع التحزيم.
        /// </summary>
        internal static string PackagingTypeName {
            get {
                return ResourceManager.GetString("PackagingTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود الحزمة.
        /// </summary>
        internal static string PackCode {
            get {
                return ResourceManager.GetString("PackCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عدد الحزم.
        /// </summary>
        internal static string PackCount {
            get {
                return ResourceManager.GetString("PackCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل طريقة الحساب.
        /// </summary>
        internal static string PackingCalculationTypeID {
            get {
                return ResourceManager.GetString("PackingCalculationTypeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to طريقة الحساب.
        /// </summary>
        internal static string PackingCalculationTypeName {
            get {
                return ResourceManager.GetString("PackingCalculationTypeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مخصص من.
        /// </summary>
        internal static string PackingParentID {
            get {
                return ResourceManager.GetString("PackingParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to القيمة.
        /// </summary>
        internal static string PackingValue {
            get {
                return ResourceManager.GetString("PackingValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحزمة.
        /// </summary>
        internal static string PackNumber {
            get {
                return ResourceManager.GetString("PackNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم التسلسل.
        /// </summary>
        internal static string PackSerial {
            get {
                return ResourceManager.GetString("PackSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ParentID.
        /// </summary>
        internal static string ParentID {
            get {
                return ResourceManager.GetString("ParentID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كلمة المرور.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كمية الطباعة للنموذج الواحد.
        /// </summary>
        internal static string PrintsForOneModel {
            get {
                return ResourceManager.GetString("PrintsForOneModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكر هذا المتصفح؟.
        /// </summary>
        internal static string RememberBrowser {
            get {
                return ResourceManager.GetString("RememberBrowser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تذكرني.
        /// </summary>
        internal static string RememberMe {
            get {
                return ResourceManager.GetString("RememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestOrder.
        /// </summary>
        internal static string RequestOrder {
            get {
                return ResourceManager.GetString("RequestOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestPreparationStatusID.
        /// </summary>
        internal static string RequestPreparationStatusID {
            get {
                return ResourceManager.GetString("RequestPreparationStatusID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to حالة الطلب.
        /// </summary>
        internal static string RequestPreparationStatusName {
            get {
                return ResourceManager.GetString("RequestPreparationStatusName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestWithdrawDetailID.
        /// </summary>
        internal static string RequestWithdrawDetailID {
            get {
                return ResourceManager.GetString("RequestWithdrawDetailID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestWithdrawDetailItemID.
        /// </summary>
        internal static string RequestWithdrawDetailItemID {
            get {
                return ResourceManager.GetString("RequestWithdrawDetailItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestWithdrawDetailItemModelID.
        /// </summary>
        internal static string RequestWithdrawDetailItemModelID {
            get {
                return ResourceManager.GetString("RequestWithdrawDetailItemModelID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RequestWithdrawID.
        /// </summary>
        internal static string RequestWithdrawID {
            get {
                return ResourceManager.GetString("RequestWithdrawID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to يرجي إدخال {0}.
        /// </summary>
        internal static string RequiredValidation {
            get {
                return ResourceManager.GetString("RequiredValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowGuid.
        /// </summary>
        internal static string RowGuid {
            get {
                return ResourceManager.GetString("RowGuid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedExamsNeededForA3.
        /// </summary>
        internal static string ShippedExamsNeededForA3 {
            get {
                return ResourceManager.GetString("ShippedExamsNeededForA3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedExamsNeededForA4.
        /// </summary>
        internal static string ShippedExamsNeededForA4 {
            get {
                return ResourceManager.GetString("ShippedExamsNeededForA4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedExamsNeededForCD.
        /// </summary>
        internal static string ShippedExamsNeededForCD {
            get {
                return ResourceManager.GetString("ShippedExamsNeededForCD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippedPrintsForOneModel.
        /// </summary>
        internal static string ShippedPrintsForOneModel {
            get {
                return ResourceManager.GetString("ShippedPrintsForOneModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود حقيبة الشحن.
        /// </summary>
        internal static string ShippingBagCode {
            get {
                return ResourceManager.GetString("ShippingBagCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingBagID.
        /// </summary>
        internal static string ShippingBagID {
            get {
                return ResourceManager.GetString("ShippingBagID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShippingBagItemID.
        /// </summary>
        internal static string ShippingBagItemID {
            get {
                return ResourceManager.GetString("ShippingBagItemID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to رقم الحقيبة.
        /// </summary>
        internal static string ShippingBagSerial {
            get {
                return ResourceManager.GetString("ShippingBagSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to بداية التسلسل.
        /// </summary>
        internal static string StartBookSerial {
            get {
                return ResourceManager.GetString("StartBookSerial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to تاريخ البدء.
        /// </summary>
        internal static string StartDate {
            get {
                return ResourceManager.GetString("StartDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to كود المنطقة الإدارية.
        /// </summary>
        internal static string StateProvinceCode {
            get {
                return ResourceManager.GetString("StateProvinceCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل المنطقة الإدارية.
        /// </summary>
        internal static string StateProvinceId {
            get {
                return ResourceManager.GetString("StateProvinceId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to المنطقة الادارية.
        /// </summary>
        internal static string StateProvinceName {
            get {
                return ResourceManager.GetString("StateProvinceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل المنطقة.
        /// </summary>
        internal static string StateRegionID {
            get {
                return ResourceManager.GetString("StateRegionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} يجب ان يكون علي الأقل {2} حرف.
        /// </summary>
        internal static string StringLengthValidation {
            get {
                return ResourceManager.GetString("StringLengthValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مسلسل الجنس.
        /// </summary>
        internal static string StudentGenderID {
            get {
                return ResourceManager.GetString("StudentGenderID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الجنس.
        /// </summary>
        internal static string StudentGenderName {
            get {
                return ResourceManager.GetString("StudentGenderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to زمن القسم الواحد.
        /// </summary>
        internal static string TimeForSection {
            get {
                return ResourceManager.GetString("TimeForSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to العدد الإجمالي.
        /// </summary>
        internal static string Total {
            get {
                return ResourceManager.GetString("Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to مجموع الحزم.
        /// </summary>
        internal static string TotalPacks {
            get {
                return ResourceManager.GetString("TotalPacks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to اسم المستخدم.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to وزن الحزمة.
        /// </summary>
        internal static string Weight {
            get {
                return ResourceManager.GetString("Weight", resourceCulture);
            }
        }
    }
}
