<?xml version="1.0" encoding="utf-8"?><Database Name="Qiyas" Class="QiyasLinqDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=RBM-MLAP;Initial Catalog=Qiyas;User ID=sa" SettingsObjectName="Qiyas.DataAccessLayer.Properties.Settings" SettingsPropertyName="QiyasConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="Person.BusinessEntity" Member="BusinessEntities">
    <Type Name="BusinessEntity">
      <Column Name="BusinessEntityId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RowGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="BusinessEntity_Person" Member="Person" ThisKey="BusinessEntityId" OtherKey="BusinessEntityId" Type="Person" Cardinality="One" />
    </Type>
  </Table>
  <Table Name="Person.Person" Member="Persons">
    <Type Name="Person">
      <Column Name="BusinessEntityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FirstName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MiddleName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="LastName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="DisplayName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Title" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="NameStyle" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="EmailPromotion" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RowGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="NationalityCode" Type="System.String" DbType="Char(3)" CanBeNull="true" />
      <Column Name="Gender" Type="System.Char" DbType="Char(1)" CanBeNull="true" />
      <Column Name="DateofBirth" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PersonImage" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Association Name="Person_UserClaim" Member="UserClaims" ThisKey="BusinessEntityId" OtherKey="UserId" Type="UserClaim" />
      <Association Name="Person_UserLoginProvider" Member="UserLoginProviders" ThisKey="BusinessEntityId" OtherKey="UserId" Type="UserLoginProvider" />
      <Association Name="Person_Credential" Member="Credential" ThisKey="BusinessEntityId" OtherKey="BusinessEntityId" Type="Credential" Cardinality="One" />
      <Association Name="BusinessEntity_Person" Member="BusinessEntity" ThisKey="BusinessEntityId" OtherKey="BusinessEntityId" Type="BusinessEntity" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="RoleSecurity.UserClaim" Member="UserClaims">
    <Type Name="UserClaim">
      <Column Name="UserClaimId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ClaimValue" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ClaimType" Type="System.String" DbType="NChar(150)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Person_UserClaim" Member="Person" ThisKey="UserId" OtherKey="BusinessEntityId" Type="Person" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="RoleSecurity.UserLoginProvider" Member="UserLoginProviders">
    <Type Name="UserLoginProvider">
      <Column Name="UserLoginProviderId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="UserId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LoginProvider" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="ProviderKey" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Person_UserLoginProvider" Member="Person" ThisKey="UserId" OtherKey="BusinessEntityId" Type="Person" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="RoleSecurity.Role" Member="Roles">
    <Type Name="Role">
      <Column Name="RoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="RowGuid" Type="System.Guid" DbType="UniqueIdentifier" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_PersonRole" Member="PersonRoles" ThisKey="RoleId" OtherKey="RoleId" Type="PersonRole" />
    </Type>
  </Table>
  <Table Name="RoleSecurity.PersonRole" Member="PersonRoles">
    <Type Name="PersonRole">
      <Column Name="PersonRoleId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RoleId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PersonId" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Role_PersonRole" Member="Role" ThisKey="RoleId" OtherKey="RoleId" Type="Role" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="Credential_PersonRole" Member="Credential" ThisKey="PersonId" OtherKey="BusinessEntityId" Type="Credential" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="Person.Credential" Member="Credentials">
    <Type Name="Credential">
      <Column Name="BusinessEntityId" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Username" Type="System.String" DbType="NVarChar(60) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordHash" Type="System.String" DbType="NVarChar(128) NOT NULL" CanBeNull="false" />
      <Column Name="PasswordSalt" Type="System.String" DbType="NVarChar(10)" CanBeNull="true" />
      <Column Name="ActivationCode" Type="System.String" DbType="NVarChar(128)" CanBeNull="true" />
      <Column Name="IsActivated" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit NOT NULL" CanBeNull="false" />
      <Column Name="RowGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="EmailConfirmationCode" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="EmailConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="PhoneNumber" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmationCode" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="PhoneNumberConfirmed" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockoutEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="TwoFactorEnabled" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="LockoutEndDateUtc" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="AccessFailedCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Credential_PersonRole" Member="PersonRoles" ThisKey="BusinessEntityId" OtherKey="PersonId" Type="PersonRole" />
      <Association Name="Person_Credential" Member="Person" ThisKey="BusinessEntityId" OtherKey="BusinessEntityId" Type="Person" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.StudentGender" Member="StudentGenders">
    <Type Name="StudentGender">
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="StudentGender_ExamPeriod" Member="ExamPeriods" ThisKey="StudentGenderID" OtherKey="StudentGenderID" Type="ExamPeriod" />
      <Association Name="StudentGender_ExamCenter" Member="ExamCenters" ThisKey="StudentGenderID" OtherKey="StudentGenderID" Type="ExamCenter" />
      <Association Name="StudentGender_Exam" Member="Exams" ThisKey="StudentGenderID" OtherKey="StudentGenderID" Type="Exam" />
    </Type>
  </Table>
  <Table Name="PPM.PackagingType" Member="PackagingTypes">
    <Type Name="PackagingType">
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Total" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="PackagingType_RequestWithdrawDetailItem" Member="RequestWithdrawDetailItems" ThisKey="PackagingTypeID" OtherKey="PackagingTypeID" Type="RequestWithdrawDetailItem" />
      <Association Name="PackagingType_BookPackingOperation" Member="BookPackingOperations" ThisKey="PackagingTypeID" OtherKey="PackagingTypeID" Type="BookPackingOperation" />
    </Type>
  </Table>
  <Table Name="PPM.OperationStatus" Member="OperationStatus">
    <Type Name="OperationStatus">
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="OperationStatus_BookPrintingOperation" Member="BookPrintingOperations" ThisKey="OperationStatusID" OtherKey="OperationStatusID" Type="BookPrintingOperation" />
    </Type>
  </Table>
  <Table Name="PPM.ExamType" Member="ExamTypes">
    <Type Name="ExamType">
      <Column Name="ExaminationTypeID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ExamType_ExamSpeciality" Member="ExamSpecialities" ThisKey="ExaminationTypeID" OtherKey="ExamTypeID" Type="ExamSpeciality" />
      <Association Name="ExamType_ExamPeriod" Member="ExamPeriods" ThisKey="ExaminationTypeID" OtherKey="ExamTypeID" Type="ExamPeriod" />
    </Type>
  </Table>
  <Table Name="PPM.ExamSpeciality" Member="ExamSpecialities">
    <Type Name="ExamSpeciality">
      <Column Name="ExamSpecialityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ExamSpeciality_Exam" Member="Exams" ThisKey="ExamSpecialityID" OtherKey="ExamSpecialityID" Type="Exam" />
      <Association Name="ExamType_ExamSpeciality" Member="ExamType" ThisKey="ExamTypeID" OtherKey="ExaminationTypeID" Type="ExamType" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.ExamPeriod" Member="ExamPeriods">
    <Type Name="ExamPeriod">
      <Column Name="ExamPeriodID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamYear" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="EndDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ExamPeriod_ExamCenterRequiredExam" Member="ExamCenterRequiredExams" ThisKey="ExamPeriodID" OtherKey="ExamPeriodID" Type="ExamCenterRequiredExam" />
      <Association Name="ExamType_ExamPeriod" Member="ExamType" ThisKey="ExamTypeID" OtherKey="ExaminationTypeID" Type="ExamType" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="StudentGender_ExamPeriod" Member="StudentGender" ThisKey="StudentGenderID" OtherKey="StudentGenderID" Type="StudentGender" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="Person.CountryRegion" Member="CountryRegions">
    <Type Name="CountryRegion">
      <Column Name="CountryRegionCode" Type="System.String" DbType="Char(3) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="CountryRegion_StateProvince" Member="StateProvinces" ThisKey="CountryRegionCode" OtherKey="CountryRegionCode" Type="StateProvince" />
    </Type>
  </Table>
  <Table Name="Person.StateProvince" Member="StateProvinces">
    <Type Name="StateProvince">
      <Column Name="StateProvinceId" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateProvinceCode" Type="System.String" DbType="NChar(3)" CanBeNull="true" />
      <Column Name="CountryRegionCode" Type="System.String" DbType="Char(3) NOT NULL" CanBeNull="false" />
      <Column Name="IsOnlyStateProvince" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="RowGuid" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" CanBeNull="false" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime NOT NULL" CanBeNull="false" />
      <Association Name="StateProvince_City" Member="Cities" ThisKey="StateProvinceId" OtherKey="StateRegionID" Type="City" />
      <Association Name="CountryRegion_StateProvince" Member="CountryRegion" ThisKey="CountryRegionCode" OtherKey="CountryRegionCode" Type="CountryRegion" IsForeignKey="true" DeleteRule="CASCADE" DeleteOnNull="true" />
    </Type>
  </Table>
  <Table Name="Person.City" Member="Cities">
    <Type Name="City">
      <Column Name="CityID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="StateRegionID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="City_ExamCenter" Member="ExamCenters" ThisKey="CityID" OtherKey="CityID" Type="ExamCenter" />
      <Association Name="StateProvince_City" Member="StateProvince" ThisKey="StateRegionID" OtherKey="StateProvinceId" Type="StateProvince" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.ExamCenter" Member="ExamCenters">
    <Type Name="ExamCenter">
      <Column Name="ExaminationCenterID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CenterCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ExamCenter_ExamCenterRequiredExam" Member="ExamCenterRequiredExams" ThisKey="ExaminationCenterID" OtherKey="ExamCenterID" Type="ExamCenterRequiredExam" />
      <Association Name="City_ExamCenter" Member="City" ThisKey="CityID" OtherKey="CityID" Type="City" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="StudentGender_ExamCenter" Member="StudentGender" ThisKey="StudentGenderID" OtherKey="StudentGenderID" Type="StudentGender" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewExamCenter" Member="ViewExamCenters">
    <Type Name="ViewExamCenter">
      <Column Name="ExaminationCenterID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="CenterCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="CityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="StateRegionID" AutoSync="Never" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="CityName" AutoSync="Never" Type="System.String" DbType="NVarChar(50)" IsDbGenerated="true" CanBeNull="true" />
      <Column Name="StateProvinceName" AutoSync="Never" Type="System.String" DbType="NVarChar(50) NOT NULL" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CountryName" AutoSync="Never" Type="System.String" DbType="NVarChar(50) NOT NULL" IsDbGenerated="true" CanBeNull="false" />
    </Type>
  </Table>
  <Table Name="PPM.ExamModel" Member="ExamModels">
    <Type Name="ExamModel">
      <Column Name="ExamModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ExamModel_ExamModelItem" Member="ExamModelItems" ThisKey="ExamModelID" OtherKey="ExamModelID" Type="ExamModelItem" />
      <Association Name="ExamModel_BookPackItemModel" Member="BookPackItemModels" ThisKey="ExamModelID" OtherKey="ExamModelID" Type="BookPackItemModel" />
      <Association Name="ExamModel_RequestWithdrawDetailItemModel" Member="RequestWithdrawDetailItemModels" ThisKey="ExamModelID" OtherKey="ExamModelID" Type="RequestWithdrawDetailItemModel" />
    </Type>
  </Table>
  <Table Name="dbo.ExamView" Member="ExamViews">
    <Type Name="ExamView">
      <Column Name="ExamID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ExamSpecialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofSections" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeForSection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ExamSpecialityName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.PackageWeight" Member="PackageWeights">
    <Type Name="PackageWeight">
      <Column Name="PackageWeightID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PackageCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="BookPackItem_PackageWeight" Member="BookPackItem" ThisKey="PackageCode" OtherKey="BookPackItemID" Type="BookPackItem" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.Exam" Member="Exams">
    <Type Name="Exam">
      <Column Name="ExamID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(250)" CanBeNull="true" />
      <Column Name="ExamSpecialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofSections" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TimeForSection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="Exam_ExamModelItem" Member="ExamModelItems" ThisKey="ExamID" OtherKey="ExamID" Type="ExamModelItem" />
      <Association Name="Exam_BookPrintingOperation" Member="BookPrintingOperations" ThisKey="ExamID" OtherKey="ExamID" Type="BookPrintingOperation" />
      <Association Name="ExamSpeciality_Exam" Member="ExamSpeciality" ThisKey="ExamSpecialityID" OtherKey="ExamSpecialityID" Type="ExamSpeciality" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="StudentGender_Exam" Member="StudentGender" ThisKey="StudentGenderID" OtherKey="StudentGenderID" Type="StudentGender" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="PPM.ExamModelItem" Member="ExamModelItems">
    <Type Name="ExamModelItem">
      <Column Name="ExamModelItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Exam_ExamModelItem" Member="Exam" ThisKey="ExamID" OtherKey="ExamID" Type="Exam" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ExamModel_ExamModelItem" Member="ExamModel" ThisKey="ExamModelID" OtherKey="ExamModelID" Type="ExamModel" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.PackingCalculationType" Member="PackingCalculationTypes">
    <Type Name="PackingCalculationType">
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PackingCalculationType_BookPackingOperation" Member="BookPackingOperations" ThisKey="PackingCalculationTypeID" OtherKey="PackingCalculationTypeID" Type="BookPackingOperation" />
    </Type>
  </Table>
  <Table Name="PPM.BookPackItemModel" Member="BookPackItemModels">
    <Type Name="BookPackItemModel">
      <Column Name="BookPackItemModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ExamModel_BookPackItemModel" Member="ExamModel" ThisKey="ExamModelID" OtherKey="ExamModelID" Type="ExamModel" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="BookPackItem_BookPackItemModel" Member="BookPackItem" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItem" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.BookPackItemOperation" Member="BookPackItemOperations">
    <Type Name="BookPackItemOperation">
      <Column Name="BookPackItemOperationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllocatedFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookPackItem_BookPackItemOperation" Member="BookPackItem" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItem" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.ContainerRequest" Member="ContainerRequests">
    <Type Name="ContainerRequest">
      <Column Name="ContainerRequestID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ContainerRequest_ContainerRequestPack" Member="ContainerRequestPacks" ThisKey="ContainerRequestID" OtherKey="ContainerRequestID" Type="ContainerRequestPack" />
      <Association Name="ExamCenterRequiredExam_ContainerRequest" Member="ExamCenterRequiredExam" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ExamCenterRequiredExam" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.ContainerRequestPack" Member="ContainerRequestPacks">
    <Type Name="ContainerRequestPack">
      <Column Name="ContainerRequestPackID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ContainerRequestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ContainerRequest_ContainerRequestPack" Member="ContainerRequest" ThisKey="ContainerRequestID" OtherKey="ContainerRequestID" Type="ContainerRequest" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="BookPackItem_ContainerRequestPack" Member="BookPackItem" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItem" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="PPM.PackingCalculationType" Member="PackingCalculationType1s">
    <Type Name="PackingCalculationType1">
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="PackingCalculationType1_BookPackingOperation" Member="BookPackingOperations" ThisKey="PackingCalculationTypeID" OtherKey="PackingCalculationTypeID" Type="BookPackingOperation" />
    </Type>
  </Table>
  <Table Name="PPM.RequestPreparationStatus" Member="RequestPreparationStatus">
    <Type Name="RequestPreparationStatus">
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Association Name="RequestPreparationStatus_ExamCenterRequiredExam" Member="ExamCenterRequiredExams" ThisKey="RequestPreparationStatusID" OtherKey="RequestPreparationStatusID" Type="ExamCenterRequiredExam" />
      <Association Name="RequestPreparationStatus_RequestWithdrawDetail" Member="RequestWithdrawDetails" ThisKey="RequestPreparationStatusID" OtherKey="RequestPreparationStatusID" Type="RequestWithdrawDetail" />
    </Type>
  </Table>
  <Table Name="PPM.ShippingBagItem" Member="ShippingBagItems">
    <Type Name="ShippingBagItem">
      <Column Name="ShippingBagItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ShippingBagID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookPackItem_ShippingBagItem" Member="BookPackItem" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItem" IsForeignKey="true" />
      <Association Name="ShippingBag_ShippingBagItem" Member="ShippingBag" ThisKey="ShippingBagID" OtherKey="ShippingBagID" Type="ShippingBag" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.PackageWeightView" Member="PackageWeightViews">
    <Type Name="PackageWeightView">
      <Column Name="PackageWeightID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PackageCode" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.BookPrintingOperation" Member="BookPrintingOperations">
    <Type Name="BookPrintingOperation">
      <Column Name="BookPrintingOperationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="TotalPacks" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TotalExamModels" Type="System.Int32" DbType="Int" IsDbGenerated="true" CanBeNull="true" UpdateCheck="Never" />
      <Association Name="BookPrintingOperation_BookPackingOperation" Member="BookPackingOperations" ThisKey="BookPrintingOperationID" OtherKey="BookPrintingOperationID" Type="BookPackingOperation" />
      <Association Name="Exam_BookPrintingOperation" Member="Exam" ThisKey="ExamID" OtherKey="ExamID" Type="Exam" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="OperationStatus_BookPrintingOperation" Member="OperationStatus" ThisKey="OperationStatusID" OtherKey="OperationStatusID" Type="OperationStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="PPM.BookRepackPackageItem" Member="BookRepackPackageItems">
    <Type Name="BookRepackPackageItem">
      <Column Name="BookRepackPackageItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookRepackPackageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookRepackPackage_BookRepackPackageItem" Member="BookRepackPackage" ThisKey="BookRepackPackageID" OtherKey="BookRepackPackageID" Type="BookRepackPackage" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="BookPackItem_BookRepackPackageItem" Member="BookPackItem" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItem" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.BookRepackPackage" Member="BookRepackPackages">
    <Type Name="BookRepackPackage">
      <Column Name="BookRepackPackageID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookRepackPackage_BookRepackPackageItem" Member="BookRepackPackageItems" ThisKey="BookRepackPackageID" OtherKey="BookRepackPackageID" Type="BookRepackPackageItem" />
    </Type>
  </Table>
  <Table Name="dbo.ViewBookPackItemComplete" Member="ViewBookPackItemCompletes">
    <Type Name="ViewBookPackItemComplete">
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookPackingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllocatedFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPrintingOperationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageOperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExamModels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPacks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="ExamSpecialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofSections" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TimeForSection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BooksCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeBooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewRepackPackageItems" Member="ViewRepackPackageItems">
    <Type Name="ViewRepackPackageItem">
      <Column Name="BookRepackPackageItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookRepackPackageID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BooksCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExamModels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeBooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewBookPackItemPrintSub" Member="ViewBookPackItemPrintSubs">
    <Type Name="ViewBookPackItemPrintSub">
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookPackItemOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Speciality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModelandNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Expr1" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.BookPackItem" Member="BookPackItems">
    <Type Name="BookPackItem">
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="BookPackingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentBookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookPackItem_PackageWeight" Member="PackageWeights" ThisKey="BookPackItemID" OtherKey="PackageCode" Type="PackageWeight" />
      <Association Name="BookPackItem_BookPackItemModel" Member="BookPackItemModels" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItemModel" />
      <Association Name="BookPackItem_BookPackItemOperation" Member="BookPackItemOperations" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookPackItemOperation" />
      <Association Name="BookPackItem_ContainerRequestPack" Member="ContainerRequestPacks" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="ContainerRequestPack" />
      <Association Name="BookPackItem_ShippingBagItem" Member="ShippingBagItems" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="ShippingBagItem" />
      <Association Name="BookPackItem_BookRepackPackageItem" Member="BookRepackPackageItems" ThisKey="BookPackItemID" OtherKey="BookPackItemID" Type="BookRepackPackageItem" />
      <Association Name="BookPackingOperation_BookPackItem" Member="BookPackingOperation" ThisKey="BookPackingOperationID" OtherKey="BookPackingOperationID" Type="BookPackingOperation" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.ExamCenterRequiredExams" Member="ExamCenterRequiredExams">
    <Type Name="ExamCenterRequiredExam">
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamPeriodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCenterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileNeedsPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ExamCenterRequiredExam_ContainerRequest" Member="ContainerRequests" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ContainerRequest" />
      <Association Name="ExamCenterRequiredExam_ExamRequirementItem" Member="ExamRequirementItems" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ExamRequirementItem" />
      <Association Name="ExamCenterRequiredExam_RequestWithdraw" Member="RequestWithdraws" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="RequestWithdraw" />
      <Association Name="ExamCenterRequiredExam_ShippingBag" Member="ShippingBags" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ShippingBag" />
      <Association Name="ExamCenter_ExamCenterRequiredExam" Member="ExamCenter" ThisKey="ExamCenterID" OtherKey="ExaminationCenterID" Type="ExamCenter" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="ExamPeriod_ExamCenterRequiredExam" Member="ExamPeriod" ThisKey="ExamPeriodID" OtherKey="ExamPeriodID" Type="ExamPeriod" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="RequestPreparationStatus_ExamCenterRequiredExam" Member="RequestPreparationStatus" ThisKey="RequestPreparationStatusID" OtherKey="RequestPreparationStatusID" Type="RequestPreparationStatus" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="PPM.ExamRequirementItem" Member="ExamRequirementItems">
    <Type Name="ExamRequirementItem">
      <Column Name="ExamRequirementItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ExamRequirementItem_RequestWithdrawDetail" Member="RequestWithdrawDetails" ThisKey="ExamRequirementItemID" OtherKey="ExamRequirementItemID" Type="RequestWithdrawDetail" />
      <Association Name="ExamCenterRequiredExam_ExamRequirementItem" Member="ExamCenterRequiredExam" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ExamCenterRequiredExam" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.RequestWithdraw" Member="RequestWithdraws">
    <Type Name="RequestWithdraw">
      <Column Name="RequestWithdrawID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestOrder" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="RequestWithdraw_RequestWithdrawDetail" Member="RequestWithdrawDetails" ThisKey="RequestWithdrawID" OtherKey="RequestWithdrawID" Type="RequestWithdrawDetail" />
      <Association Name="ExamCenterRequiredExam_RequestWithdraw" Member="ExamCenterRequiredExam" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ExamCenterRequiredExam" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.RequestWithdrawDetail" Member="RequestWithdrawDetails">
    <Type Name="RequestWithdrawDetail">
      <Column Name="RequestWithdrawDetailID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestWithdrawID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamRequirementItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippedPrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippedExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippedExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippedExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="RequestWithdrawDetail_RequestWithdrawDetailItem" Member="RequestWithdrawDetailItems" ThisKey="RequestWithdrawDetailID" OtherKey="RequestWithdrawDetailID" Type="RequestWithdrawDetailItem" />
      <Association Name="ExamRequirementItem_RequestWithdrawDetail" Member="ExamRequirementItem" ThisKey="ExamRequirementItemID" OtherKey="ExamRequirementItemID" Type="ExamRequirementItem" IsForeignKey="true" />
      <Association Name="RequestPreparationStatus_RequestWithdrawDetail" Member="RequestPreparationStatus" ThisKey="RequestPreparationStatusID" OtherKey="RequestPreparationStatusID" Type="RequestPreparationStatus" IsForeignKey="true" />
      <Association Name="RequestWithdraw_RequestWithdrawDetail" Member="RequestWithdraw" ThisKey="RequestWithdrawID" OtherKey="RequestWithdrawID" Type="RequestWithdraw" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.RemainingExamRequirementItemForWithdraw" Member="RemainingExamRequirementItemForWithdraws">
    <Type Name="RemainingExamRequirementItemForWithdraw">
      <Column Name="ExamRequirementItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewCurrentPackStockExistence" Member="ViewCurrentPackStockExistences">
    <Type Name="ViewCurrentPackStockExistence">
      <Column Name="PackCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewReservedPacks" Member="ViewReservedPacks">
    <Type Name="ViewReservedPack">
      <Column Name="PackCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.RequestWithdrawDetailItem" Member="RequestWithdrawDetailItems">
    <Type Name="RequestWithdrawDetailItem">
      <Column Name="RequestWithdrawDetailItemID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestWithdrawDetailID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="RequestWithdrawDetailItem_RequestWithdrawDetailItemModel" Member="RequestWithdrawDetailItemModels" ThisKey="RequestWithdrawDetailItemID" OtherKey="RequestWithdrawDetailItemID" Type="RequestWithdrawDetailItemModel" />
      <Association Name="PackagingType_RequestWithdrawDetailItem" Member="PackagingType" ThisKey="PackagingTypeID" OtherKey="PackagingTypeID" Type="PackagingType" IsForeignKey="true" />
      <Association Name="RequestWithdrawDetail_RequestWithdrawDetailItem" Member="RequestWithdrawDetail" ThisKey="RequestWithdrawDetailID" OtherKey="RequestWithdrawDetailID" Type="RequestWithdrawDetail" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="PPM.RequestWithdrawDetailItemModel" Member="RequestWithdrawDetailItemModels">
    <Type Name="RequestWithdrawDetailItemModel">
      <Column Name="RequestWithdrawDetailItemModelID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="RequestWithdrawDetailItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="ExamModel_RequestWithdrawDetailItemModel" Member="ExamModel" ThisKey="ExamModelID" OtherKey="ExamModelID" Type="ExamModel" IsForeignKey="true" />
      <Association Name="RequestWithdrawDetailItem_RequestWithdrawDetailItemModel" Member="RequestWithdrawDetailItem" ThisKey="RequestWithdrawDetailItemID" OtherKey="RequestWithdrawDetailItemID" Type="RequestWithdrawDetailItem" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Table Name="dbo.ViewWithdrawalReport" Member="ViewWithdrawalReports">
    <Type Name="ViewWithdrawalReport">
      <Column Name="RequestWithdrawDetailID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="RequestWithdrawID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamRequirementItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamModel" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamPeriodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCenterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PeriodName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CenterName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewContainerRequest" Member="ViewContainerRequests">
    <Type Name="ViewContainerRequest">
      <Column Name="ContainerRequestPackID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ContainerRequestID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookPackingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StartBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllocatedFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPrintingOperationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA3" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForA4" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamsNeededForCD" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageOperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExamModels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPacks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="ExamSpecialityID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="StudentGenderID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofPages" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofSections" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Notes" Type="System.String" DbType="NText" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="TimeForSection" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="IsActive" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="BooksCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeBooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.BookPackingOperation" Member="BookPackingOperations">
    <Type Name="BookPackingOperation">
      <Column Name="BookPackingOperationID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookPrintingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllocatedFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="NumberofBooksPerModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotalPerModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="BookPackingOperation_BookPackItem" Member="BookPackItems" ThisKey="BookPackingOperationID" OtherKey="BookPackingOperationID" Type="BookPackItem" />
      <Association Name="BookPackingOperation_BookPackingOperation" Member="BookPackingOperations" ThisKey="BookPackingOperationID" OtherKey="PackingParentID" Type="BookPackingOperation" />
      <Association Name="BookPackingOperation_BookPackingOperation" Member="BookPackingOperation1" ThisKey="PackingParentID" OtherKey="BookPackingOperationID" Type="BookPackingOperation" IsForeignKey="true" />
      <Association Name="BookPrintingOperation_BookPackingOperation" Member="BookPrintingOperation" ThisKey="BookPrintingOperationID" OtherKey="BookPrintingOperationID" Type="BookPrintingOperation" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PackagingType_BookPackingOperation" Member="PackagingType" ThisKey="PackagingTypeID" OtherKey="PackagingTypeID" Type="PackagingType" IsForeignKey="true" DeleteRule="CASCADE" />
      <Association Name="PackingCalculationType_BookPackingOperation" Member="PackingCalculationType" ThisKey="PackingCalculationTypeID" OtherKey="PackingCalculationTypeID" Type="PackingCalculationType" IsForeignKey="true" />
      <Association Name="PackingCalculationType1_BookPackingOperation" Member="PackingCalculationType1" ThisKey="PackingCalculationTypeID" OtherKey="PackingCalculationTypeID" Type="PackingCalculationType1" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewShippingBagItems" Member="ViewShippingBagItems">
    <Type Name="ViewShippingBagItem">
      <Column Name="ShippingBagItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ShippingBagID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PrintsForOneModel" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalExamModels" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="TotalPacks" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="BooksCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewBookPackItemPrint" Member="ViewBookPackItemPrints">
    <Type Name="ViewBookPackItemPrint">
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="BookPackingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="PackSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Weight" Type="System.Decimal" DbType="Decimal(18,2)" CanBeNull="true" />
      <Column Name="OperationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Speciality" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ModelandNumber" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="BookPrintingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTypeName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="StartBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="LastBookSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildPackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildExamModelCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ChildBooksPerPackage" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.ViewExamCenterRequiredExams" Member="ViewExamCenterRequiredExams">
    <Type Name="ViewExamCenterRequiredExam">
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="ExamPeriodID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamCenterID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="RequestPreparationStatusID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="FileNeedsPath" Type="System.String" DbType="NVarChar(500)" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ExamPeriodName" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ExamCenterCode" Type="System.String" DbType="NVarChar(12)" CanBeNull="true" />
      <Column Name="ExamCenterName" Type="System.String" DbType="NVarChar(150)" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="PPM.ShippingBag" Member="ShippingBags">
    <Type Name="ShippingBag">
      <Column Name="ShippingBagID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="ExamCenterRequiredExamsID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ShippingBagCode" Type="System.String" DbType="NVarChar(20)" CanBeNull="true" />
      <Column Name="ShippingBagSerial" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="BookCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackCount" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedBy" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Association Name="ShippingBag_ShippingBagItem" Member="ShippingBagItems" ThisKey="ShippingBagID" OtherKey="ShippingBagID" Type="ShippingBagItem" />
      <Association Name="ExamCenterRequiredExam_ShippingBag" Member="ExamCenterRequiredExam" ThisKey="ExamCenterRequiredExamsID" OtherKey="ExamCenterRequiredExamsID" Type="ExamCenterRequiredExam" IsForeignKey="true" DeleteRule="CASCADE" />
    </Type>
  </Table>
  <Function Name="dbo.DeleteExamModelItemByExamID" Method="DeleteExamModelItemByExamID">
    <Parameter Name="ExamID" Parameter="examID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageByPrintingID" Method="GetTotalPrintingPackageByPrintingID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageA3ByPrintingID" Method="GetTotalPrintingPackageA3ByPrintingID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExamModelCount" Method="GetExamModelCount" IsComposable="true">
    <Parameter Name="ExamID" Parameter="examID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageItemsA3ByPrintingID" Method="GetTotalPrintingPackageItemsA3ByPrintingID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageItemsByPrintingID" Method="GetTotalPrintingPackageItemsByPrintingID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.DeleteBookPackingOperationByBookPrintingID" Method="DeleteBookPackingOperationByBookPrintingID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetLastPackSerialForExamID" Method="GetLastPackSerialForExamID" IsComposable="true">
    <Parameter Name="ExamID" Parameter="examID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetPackedByPrintingID" Method="GetPackedByPrintingID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetPackedByPrintingIDResult">
      <Column Name="BookPackingOperationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookPrintingOperationID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllocatedFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.CheckPackWeightComplete" Method="CheckPackWeightComplete">
    <Parameter Name="PrintID" Parameter="printID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.UpdateItemPacksBulk" Method="UpdateItemPacksBulk">
    <Parameter Name="PrintID" Parameter="printID" Type="System.Int32" DbType="Int" />
    <Parameter Name="StatusID" Parameter="statusID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetItemPackedByPackID" Method="GetItemPackedByPackID">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <ElementType Name="GetItemPackedByPackIDResult">
      <Column Name="BookPackItemOperationID" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CreatorID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="CreatedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="ModifiedByID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="ModifiedDate" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="BookPackItemID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackagingTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingCalculationTypeID" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AllocatedFrom" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="PackingValue" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackageTotal" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="PackingParentID" Type="System.Int32" DbType="Int" CanBeNull="true" />
    </ElementType>
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageByItemPackID" Method="GetTotalPrintingPackageByItemPackID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageA3ByItemPackID" Method="GetTotalPrintingPackageA3ByItemPackID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageByPackID" Method="GetTotalPrintingPackageByPackID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetTotalPrintingPackageItemsA3ByPackID" Method="GetTotalPrintingPackageItemsA3ByPackID" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetBookCountForBookPackItem" Method="GetBookCountForBookPackItem" IsComposable="true">
    <Parameter Name="BookPackItemID" Parameter="bookPackItemID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetExamModelName" Method="GetExamModelName" IsComposable="true">
    <Parameter Name="ExamID" Parameter="examID" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.GetExamModelNameFromPackItem" Method="GetExamModelNameFromPackItem" IsComposable="true">
    <Parameter Name="BookPackItemID" Parameter="bookPackItemID" Type="System.Int32" DbType="Int" />
    <Return Type="System.String" />
  </Function>
  <Function Name="dbo.GetPackedBookItemLastSerial" Method="GetPackedBookItemLastSerial" IsComposable="true">
    <Parameter Name="BookPackItemID" Parameter="bookPackItemID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetPackageBooksCountByBookPackItemId" Method="GetPackageBooksCountByBookPackItemId" IsComposable="true">
    <Parameter Name="BookPackItemID" Parameter="bookPackItemID" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.GetWithdrawRequestSerial" Method="GetWithdrawRequestSerial" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Int32" />
  </Function>
  <Function Name="dbo.HaveA3Packs" Method="HaveA3Packs" IsComposable="true">
    <Parameter Name="ID" Parameter="iD" Type="System.Int32" DbType="Int" />
    <Return Type="System.Boolean" />
  </Function>
</Database>